name: dlite

namespace:
  name: abhayganvir-helm-test

image: "drone/drone-runner-aws"
autoscalingMinInstanceCount: 1
autoscalingMaxInstanceCount: 1
port: 3000
replicas: 1
cpu: 0.5
memory: 1Gi

gcp_service_account_b64:  "ewogICJjbGllbnRfaWQiOiAiNzY0MDg2MDUxODUwLTZxcjRwNmdwaTZobjUwNnB0OGVqdXE4M2RpMzQxaHVyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwKICAiY2xpZW50X3NlY3JldCI6ICJkLUZMOTVRMTlxN01RbUZwZDdoSEQwVHkiLAogICJxdW90YV9wcm9qZWN0X2lkIjogImNpLXBsYXkiLAogICJyZWZyZXNoX3Rva2VuIjogIjEvLzBncVNzb1dLMWh3UlZDZ1lJQVJBQUdCQVNOd0YtTDlJcmpSdlZpRGctbV95N3dHb3d4aXJnRDQ4aC1HOTZpU1JzVnVNZ1VpVE9rNXR6Z1VMbW9Qcy0wZXZhOHNtWFVWOEdCeEEiLAogICJ0eXBlIjogImF1dGhvcml6ZWRfdXNlciIKfQo="

instances:
  project_id: 'ci-play'
  linux:
    amd64:
      pool_size: 1
      pool_limit: 3
      image: projects/ci-play/global/images/hosted-vm-64
      machine_type: e2-standard-4
      disk_size: 100
      zones:
        - asia-south1-b

dlite:
  linux_name: dlite-linux
  accountId: "__GLOBAL_DELEGATE_ACCOUNT_ID__"
  accountSecret: "2f6b0988b6fb3370073c3d0505baee59"
  managerEndpoint: "https://192.168.1.4:9090"
  pollIntervalMs: "1000"
  parallelWorkers: "10000"

service:
  enabled: true
  type: ClusterIP  # Change this to NodePort or LoadBalancer if needed
  port: 80         # Port on which your application is running
  targetPort: 9090 # Port on which your application is running inside the pod
