kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: go vet and unit tests
    image: golang:1
    commands:
      - go vet ./...
      - go test -cover ./...
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone
  - name: golangci-lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --timeout 500s
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone
  - name: build
    image: golang:1
    commands:
      - sh scripts/build.sh
    volumes:
      - name: cache
        path: /go
    depends_on:
      - go vet and unit tests
      - golangci-lint
  - name: compiler checks
    image: golang:1
    commands:
      - release/linux/amd64/drone-runner-aws compile --source='./test_files/drone_ubuntu.yml' test_files/drone_pool.yml
      - release/linux/amd64/drone-runner-aws compile --source='./test_files/drone_windows.yml' test_files/drone_pool.yml
    depends_on:
      - build
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: drone/drone-runner-aws
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.linux.amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
    depends_on:
      - compiler checks

volumes:
  - name: cache
    temp: {}
    
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    spec: docker/manifest.tmpl
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

depends_on:
- default
trigger:
  ref:
  - refs/heads/master
  - refs/tags/*
