kind: pipeline
name: default

steps:
  - name: build
    image: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test
    commands:
      - echo "Running inside the ECR image"
      - ./your-build-script.sh

# Registry credentials
image_pull_secrets:
  - ecr_credentials

---
kind: secret
name: ecr_credentials
get:
  path: ecr
  name: credentials
