version: "2"

linters:
  default: none
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - dupl
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
  # - nakedret (removed - too strict for this codebase)
  # - depguard (requires configuration)
  # - exportloopref (obsolete in Go 1.22+)

  settings:
    funlen:
      lines: 400
      statements: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 25
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 200
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    paths:
      - _gen\.go
    rules:
      - path: _test\.go
        linters:
          - mnd
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
      - linters:
          - gocritic
        text: "emptyStringTest:"
      - linters:
          - gosec
        text: "G104:|G115:"
      - linters:
          - revive
        text: "exported:|package-comments:|unused-parameter:|superfluous-else:"
      - linters:
          - staticcheck
        text: "^(QF|S1009)"
      - linters:
          - nolintlint
        text: "directive .* is unused"
      # Pre-existing: database/exec calls without context (structural)
      - linters:
          - noctx
        path: (store/|vmfusion/)
      # Pre-existing: package naming conventions
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
