version: "1"
instances:
  - name: ubuntu-xenial
    default: true
    type: aws   # type of instance.  aws | gcp | vmfusion | virtualbox | mac
    pool: 1    # total number of warm instances in the pool at all times
    limit: 100  # limit the total number of running servers. If exceeded block or error.
    platform:
      os: linux
      arch: amd64
    spec:
      account:
        region: us-east-2
        zone: us-east-2a
        access_key_id: AKIARLPW64RAMBHUPDWQ
        access_key_secret: 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
      ami: ami-051197ce9cbb023ea
      type: t2.nano
      network:
        security_groups:
          - sg-04dccddeaf13555d6
  - name: ubuntu-gcp
    default: true
    type: gcp   # type of instance.  aws | gcp | vmfusion | virtualbox | mac
    pool: 1    # total number of warm instances in the pool at all times
    limit: 100  # limit the total number of running servers. If exceeded block or error.
    platform:
      os: linux
      arch: amd64
    spec:
      account:
        project_id: drone-ci-289110
        json_path: /Users/eoinmcafee/.config/gcloud/application_default_credentials.json
      image: projects/windows-cloud/global/images/windows-server-2019-dc-for-containers-v20220211
      machine_type: e2-medium
      zone:
        - europe-west1-b