apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dlite.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: 
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "dlite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.global.commonAnnotations }}
        {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dlite.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.podLabels }}
        {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: init-mongo
          image: mongo:4.4
          command:
            - /bin/bash
            - '-c'
            - >
              mongo $MONGO_URI -u $MONGODB_USER -p $MONGODB_PASSWORD --eval 'db.accounts.insert({ "_id" : "__GLOBAL_DELEGATE_ACCOUNT_ID__", "companyName" : "Harness", "accountName" : "Harness Global Delegate", "accountKey" : "2f6b0988b6fb3370073c3d0505baee59", "globalDelegateAccount" : true,"isProductLed" : true})'
          env:
          {{- include "harnesscommon.dbv3.mongoEnv" (dict "ctx" $ "database" "harness" "userVariableName" "MONGODB_USER" "passwordVariableName" "MONGODB_PASSWORD") | indent 10 }}
          {{- include "harnesscommon.dbv3.mongoConnectionEnv" (dict "ctx" $ "database" "harness" "connectionURIVariableName" "MONGO_URI" "userVariableName" "MONGODB_USER" "passwordVariableName" "MONGODB_PASSWORD") | indent 10 }}
      {{- include "dlite.pullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "dlite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: dlite
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/app/drone-runner-aws", "dlite", "--pool=/etc/config/pool.yml"]
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 2Gi
            cpu: 1
        env:
        - name: DLITE_NAME
          value: {{.Values.dlite.linux_name}}
        - name: DLITE_ACCOUNT_ID
          value: {{.Values.dlite.accountId | quote}}
        - name: DLITE_ACCOUNT_SECRET
          value: {{.Values.dlite.accountSecret | quote}}
        - name: DLITE_MANAGER_ENDPOINT
          value: {{.Values.dlite.managerEndpoint}}
        - name: DLITE_PARALLEL_WORKERS
          value: {{.Values.dlite.parallelWorkers | quote}}
        - name: DLITE_POLL_INTERVAL_MILLISECS
          value: {{.Values.dlite.pollIntervalMs | quote}}
        - name: SKIP_PREPARE_SERVER
          value: "true"
        - name: DRONE_TRACE
          value: "true"
        - name: DRONE_LITE_ENGINE_PATH
          value: https://storage.googleapis.com/harness-ti/local
        volumeMounts:
        - name: pool-cfg
          mountPath: /etc/config
        - name: service-account
          mountPath: /var/run/secret
          readOnly: true
      volumes:
        - name: pool-cfg
          configMap:
            name: {{.Values.name}}
            items:
            - key: pool
              path: pool.yml
        {{- include "harnesscommon.secrets.manageAppVolumes" (dict "ctx" $ "variableName" "DLITE_GCP_SECRET_ACCOUNT" "overrideEnvName" "service-account" "path" "cloud.google.com" "defaultKubernetesSecretName" "dlite" "defaultKubernetesSecretKey" "DLITE_GCP_SECRET_ACCOUNT") | indent 8 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - dlite
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
