apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlite-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "dlite-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: dlite
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            { { - toYaml .Values.securityContext | nindent 12 } }
          ports:
            - name: http-dlite
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-dlite
              initialDelaySeconds: 40
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http-dlite
              initialDelaySeconds: 60
              timeoutSeconds: 5
              periodSeconds: 5
              failureThreshold: 8
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dlite-service
              topologyKey: "kubernetes.io/hostname"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

