apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlite-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dlite.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "dlite.selectorLabels" . | nindent 6 }}
    spec:
      {{ include "dlite.pullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "dlite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      containers:
      - command:
        - /bin/drone-runner-aws
        - dlite
        - --pool=/etc/config/pool.yml
        env:
          {{- toYaml .Values.environmentVariables | nindent 12 }}
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 8 }}
        ports:
          - name: http-dlite
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dlite-service
              topologyKey: "kubernetes.io/hostname"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

