{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dlite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dlite.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dlite
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage : {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{ end }}
{{- end }}
