FROM alpine:3.21 as alpine
RUN apk update && apk upgrade --no-cache && apk add -U --no-cache ca-certificates

FROM alpine:3.21
# Update all packages to fix CVE-2025-14017 (curl) and CVE-2025-60876 (busybox)
RUN apk update && apk upgrade --no-cache && apk add -U --no-cache curl
EXPOSE 3000

ENV GODEBUG netdns=go
ENV DRONE_PLATFORM_OS linux
ENV DRONE_PLATFORM_ARCH arm64

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ADD release/linux/arm64/drone-runner-aws-linux-arm64 /bin/drone-runner-aws
ENTRYPOINT ["/bin/drone-runner-aws"]
