kind: pipeline
type: vm
name: default

pool:
  use: windows 2019

steps:
  - name: check install
    commands:
      - $amazon = Test-Path -Path C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log
      - if ($amazon) { type C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log }
      - $azure = Test-Path -Path C:\WindowsAzure\Logs\UserdataExecution.log
      - if ($azure) { type C:\WindowsAzure\Logs\UserdataExecution.log }
      - echo "Hello World"
  - name: imagey + commands
    image: golang:1-windowsservercore
    commands:
      - go version
      - go help
      - dir c:/
      - dir c:/volumes
    volumes:
      - name: cache
        path: c:/volumes
  - name: docker status
    commands:
      - docker ps -a
  - name: ping service sleepyserver
    image: golang:1-windowsservercore
    commands:
      - ping sleepyserver

volumes:
  - name: cache
    temp: {}

services:
  - name: sleepyserver
    image: golang:1-windowsservercore
    commands:
      - powershell Start-Sleep -s 1800

depends_on:
  - unit tests
