#!/usr/bin/bash
set -e
mkdir {{ .CertDir }}

echo {{ .CACert | base64 }} | base64 -d >> {{ .CaCertPath }}
chmod 0600 {{ .CaCertPath }}

echo {{ .TLSCert | base64 }} | base64 -d  >> {{ .CertPath }}
chmod 0600 {{ .CertPath }}

echo {{ .TLSKey | base64 }} | base64 -d >> {{ .KeyPath }}
chmod 0600 {{ .KeyPath }}

echo "setting up swap space"
fallocate -l 30G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "done setting up swap space"

echo "downloading lite engine binary"
if /usr/bin/wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=2 --waitretry=2 "{{ .LiteEnginePath }}/lite-engine-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/lite-engine || /usr/bin/wget --retry-connrefused --tries=2 --waitretry=2 -nv --debug "{{ .LiteEnginePath }}/lite-engine-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/lite-engine; then
    echo "Successfully downloaded lite engine binary from primary URL."
else
    echo "Primary URL failed for lite-engine. Trying fallback URL..."
    /usr/bin/wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=5 --waitretry=5 "{{ .LiteEngineFallbackPath }}/lite-engine-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/lite-engine || /usr/bin/wget --retry-connrefused --tries=5 --waitretry=5 -nv --debug "{{ .LiteEngineFallbackPath }}/lite-engine-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/lite-engine
    echo "Successfully downloaded lite engine binary from fallback URL."
fi
chmod 777 /usr/bin/lite-engine
touch $HOME/.env
cp "/etc/environment" $HOME/.env
echo "SKIP_PREPARE_SERVER=true" >> $HOME/.env;
echo "CLOUD_DRIVER={{ .DriverName }}" >> $HOME/.env

{{ if .PluginBinaryURI }}
if wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=2 --waitretry=2 {{ .PluginBinaryURI }}/plugin-{{ .Platform.OS }}-{{ .Platform.Arch }}  -O /usr/bin/plugin || wget --retry-connrefused --tries=2 --waitretry=2 {{ .PluginBinaryURI }}/plugin-{{ .Platform.OS }}-{{ .Platform.Arch }}  -O /usr/bin/plugin; then
    echo "Successfully downloaded plugin binary from primary URL."
else
    echo "Primary URL failed for plugin. Trying fallback URL..."
    /usr/bin/wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=5 --waitretry=5 {{ .PluginBinaryFallbackURI }}/plugin-{{ .Platform.OS }}-{{ .Platform.Arch }}  -O /usr/bin/plugin || wget --retry-connrefused --tries=5 --waitretry=5 {{ .PluginBinaryFallbackURI }}/plugin-{{ .Platform.OS }}-{{ .Platform.Arch }}  -O /usr/bin/plugin
    echo "Successfully downloaded plugin binary from fallback URL."
fi
chmod 777 /usr/bin/plugin
{{ end }}

{{ if .HarnessTestBinaryURI }}
wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=10 --waitretry=10 {{ .HarnessTestBinaryURI }}/{{ .Platform.Arch }}/{{ .Platform.OS }}/bin/split_tests-{{ .Platform.OS }}_{{ .Platform.Arch }} -O /usr/bin/split_tests || wget --retry-connrefused --tries=10 --waitretry=10 {{ .HarnessTestBinaryURI }}/{{ .Platform.Arch }}/{{ .Platform.OS }}/bin/split_tests-{{ .Platform.OS }}_{{ .Platform.Arch }} -O /usr/bin/split_tests
chmod 777 /usr/bin/split_tests
{{ end }}

{{ if .AutoInjectionBinaryURI }}
mkdir -p /tmp/harness/bin
wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=10 --waitretry=10 "{{ .AutoInjectionBinaryURI }}/{{ .Platform.OS }}/{{ .Platform.Arch }}/auto-injection" -O /usr/bin/auto-injection || wget --retry-connrefused --tries=10 --waitretry=10 "{{ .AutoInjectionBinaryURI }}/{{ .Platform.OS }}/{{ .Platform.Arch }}/auto-injection" -O /usr/bin/auto-injection
chmod 777 /usr/bin/auto-injection
cp /usr/bin/auto-injection /tmp/harness/bin/auto-injection
chmod 777 /tmp/harness/bin/auto-injection
{{ end }}

{{ if .AnnotationsBinaryURI }}
if wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=2 --waitretry=2 -nv "{{ .AnnotationsBinaryURI }}hcli-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/hcli; then
    echo "Successfully downloaded annotations CLI from primary URL."
else
    echo "Primary URL failed for annotations CLI. Trying fallback URL..."
    wget --retry-connrefused --retry-on-host-error --retry-on-http-error=503,404,429 --tries=5 --waitretry=5 -nv "{{ .AnnotationsBinaryFallbackURI }}hcli-{{ .Platform.OS }}-{{ .Platform.Arch }}" -O /usr/bin/hcli
    echo "Successfully downloaded annotations CLI from fallback URL."
fi
chmod 755 /usr/bin/hcli
{{ end }}

{{ if eq .Platform.Arch "amd64" }}
if curl -fL {{ .EnvmanBinaryURI }}envman-Linux-x86_64 > /usr/bin/envman; then
	echo "Successfully downloaded envman binary from primary URL."
else
	echo "Primary URL failed for envman. Trying fallback URL..."
	curl -fL {{ .EnvmanBinaryFallbackURI }}envman-Linux-x86_64 > /usr/bin/envman
	echo "Successfully downloaded envman binary from fallback URL."
fi
chmod 777 /usr/bin/envman
{{ end }}

systemctl disable docker.service
update-alternatives --set iptables /usr/sbin/iptables-legacy
echo "restarting docker"
systemctl reset-failed docker.service
service docker start
echo "docker service restarted"

cp /etc/resolv.conf /etc/resolv_orig.conf
rm /etc/resolv.conf
echo "nameserver 127.0.0.53" > /etc/resolv.conf 
cat /etc/resolv_orig.conf >> /etc/resolv.conf
echo "options edns0 trust-ad
search ." >> /etc/resolv.conf

{{ if .Tmate.Enabled }}
mkdir /addon
if wget -nv {{ .TmateBinaryURI }}tmate-1.0-static-linux-amd64.tar.xz -O /addon/tmate.xz; then
	echo "Successfully downloaded tmate binary from primary URL."
else
	echo "Primary URL failed for tmate. Trying fallback URL..."
	wget -nv {{ .TmateBinaryFallbackURI }}tmate-1.0-static-linux-amd64.tar.xz -O /addon/tmate.xz
	echo "Successfully downloaded tmate binary from fallback URL."
fi
tar -xf /addon/tmate.xz -C /addon/
chmod 777  /addon/tmate-1.0-static-linux-amd64/tmate
mv  /addon/tmate-1.0-static-linux-amd64/tmate /addon/tmate
{{ end }}
unlink /snap/bin/google-cloud-cli.gcloud
echo "starting lite engine server"
/usr/bin/lite-engine server --env-file $HOME/.env > {{ .LiteEngineLogsPath }} 2>&1 &
echo "done starting lite engine server"